(ns graphics-magick.drawing)

;; http://www.graphicsmagick.org/wand/drawing_wand.html#clonedrawingwand

;; http://www.graphicsmagick.org/wand/drawing_wand.html#clonedrawingwand clone-drawing-wand
;; http://www.graphicsmagick.org/wand/drawing_wand.html#destroydrawingwand destroy-drawing-wand
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawannotation annotation
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawaffine affine
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawallocatewand allocate-wand
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawarc arc
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawbezier bezier
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawcircle circle
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawclearexception clear-exception
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetclippath get-clip-path
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetclippath set-clip-path
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetcliprule get-clip-rule
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetcliprule set-clip-rule
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetclipunits get-clip-units
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetexception get-exception
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetclipunits set-clip-units
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawcolor color
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawcomment comment
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawellipse ellipse
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetfillcolor get-fill-color
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetfillcolor set-fill-color
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetfillpatternurl set-fill-pattern-u-r-l
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetfillopacity get-fill-opacity
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetfillopacity set-fill-opacity
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetfillrule get-fill-rule
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetfillrule set-fill-rule
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetfont get-font
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetfont set-font
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetfontfamily get-font-family
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetfontfamily set-font-family
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetfontsize get-font-size
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetfontsize set-font-size
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetfontstretch get-font-stretch
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetfontstretch set-font-stretch
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetfontstyle get-font-style
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetfontstyle set-font-style
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetfontweight get-font-weight
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetfontweight set-font-weight
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetgravity get-gravity
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetgravity set-gravity
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawcomposite composite
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawline line
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawmatte matte
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathclose path-close
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathcurvetoabsolute path-curve-to-absolute
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathcurvetorelative path-curve-to-relative
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathcurvetoquadraticbezierabsolute path-curve-to-quadratic-bezier-absolute
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathcurvetoquadraticbezierrelative path-curve-to-quadratic-bezier-relative
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathcurvetoquadraticbeziersmoothabsolute path-curve-to-quadratic-bezier-smooth-absolute
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathcurvetoquadraticbeziersmoothrelative path-curve-to-quadratic-bezier-smooth-relative
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathcurvetosmoothabsolute path-curve-to-smooth-absolute
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathcurvetosmoothrelative path-curve-to-smooth-relative
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathellipticarcabsolute path-elliptic-arc-absolute
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathellipticarcrelative path-elliptic-arc-relative
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathfinish path-finish
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathlinetoabsolute path-line-to-absolute
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathlinetorelative path-line-to-relative
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathlinetohorizontalabsolute path-line-to-horizontal-absolute
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathlinetohorizontalrelative path-line-to-horizontal-relative
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathlinetoverticalabsolute path-line-to-vertical-absolute
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathlinetoverticalrelative path-line-to-vertical-relative
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathmovetoabsolute path-move-to-absolute
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathmovetorelative path-move-to-relative
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpathstart path-start
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpeekgraphiccontext peek-graphic-context
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpoint point
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpolygon polygon
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpolyline polyline
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpopclippath pop-clip-path
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpopdefs pop-defs
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpopgraphiccontext pop-graphic-context
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpoppattern pop-pattern
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpushclippath push-clip-path
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpushdefs push-defs
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpushgraphiccontext push-graphic-context
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawpushpattern push-pattern
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawrectangle rectangle
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawrender render
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawrotate rotate
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawroundrectangle round-rectangle
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawscale scale
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawskewx skew-x
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawskewy skew-y
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetstopcolor set-stop-color
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetstrokecolor get-stroke-color
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetstrokecolor set-stroke-color
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetstrokepatternurl set-stroke-pattern-u-r-l
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetstrokeantialias get-stroke-antialias
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetstrokeantialias set-stroke-antialias
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetstrokedasharray get-stroke-dash-array
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetstrokedasharray set-stroke-dash-array
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetstrokedashoffset get-stroke-dash-offset
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetstrokedashoffset set-stroke-dash-offset
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetstrokelinecap get-stroke-line-cap
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetstrokelinecap set-stroke-line-cap
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetstrokelinejoin get-stroke-line-join
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetstrokelinejoin set-stroke-line-join
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetstrokemiterlimit get-stroke-miter-limit
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetstrokemiterlimit set-stroke-miter-limit
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetstrokeopacity get-stroke-opacity
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetstrokeopacity set-stroke-opacity
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgetstrokewidth get-stroke-width
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetstrokewidth set-stroke-width
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgettextantialias get-text-antialias
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsettextantialias set-text-antialias
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgettextdecoration get-text-decoration
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsettextdecoration set-text-decoration
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgettextencoding get-text-encoding
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsettextencoding set-text-encoding
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawgettextundercolor get-text-under-color
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsettextundercolor set-text-under-color
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawtranslate translate
;; http://www.graphicsmagick.org/wand/drawing_wand.html#drawsetviewbox set-viewbox
;; http://www.graphicsmagick.org/wand/drawing_wand.html#newdrawingwand new-drawing-wand
