(ns graphics-magick.magick)

;; http://www.graphicsmagick.org/wand/magick_wand.html#clonemagickwand clone-wand
;; http://www.graphicsmagick.org/wand/magick_wand.html#destroymagickwand destroy-wand
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickadaptivethresholdimage adaptive-threshold-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickaddimage add-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickaddnoiseimage add-noise-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickaffinetransformimage affine-transform-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickannotateimage annotate-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickanimateimages animate-images
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickappendimages append-images
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickautoorientimage auto-orient-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickaverageimages average-images
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickblackthresholdimage black-threshold-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickblurimage blur-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickborderimage border-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickcdlimage cdl-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickcharcoalimage charcoal-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickchopimage chop-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickclearexception clear-exception
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickclipimage clip-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickclippathimage clip-path-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickcoalesceimages coalesce-images
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickcolorfloodfillimage color-floodfill-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickcolorizeimage colorize-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickcommentimage comment-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickcompareimagechannels compare-image-channels
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickcompareimages compare-images
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickcompositeimage composite-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickcontrastimage contrast-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickconvolveimage convolve-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickcropimage crop-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickcyclecolormapimage cycle-colormap-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickdeconstructimages deconstruct-images
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickdescribeimage describe-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickdespeckleimage despeckle-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickdisplayimage display-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickdisplayimages display-images
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickdrawimage draw-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickedgeimage edge-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickembossimage emboss-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickenhanceimage enhance-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickequalizeimage equalize-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickextentimage extent-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickflattenimages flatten-images
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickflipimage flip-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickflopimage flop-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickframeimage frame-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickfximage fx-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickfximagechannel fx-image-channel
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgammaimage gamma-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgammaimagechannel gamma-image-channel
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetconfigureinfo get-configure-info
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetcopyright get-copyright
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetexception get-exception
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetfilename get-filename
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgethomeurl get-home-url
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimage get-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimageattribute get-image-attribute
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagebackgroundcolor get-image-background-color
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimageblueprimary get-image-blue-primary
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagebordercolor get-image-border-color
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimageboundingbox get-image-bounding-box
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagechanneldepth get-image-channel-depth
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagechannelextrema get-image-channel-extrema
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagechannelmean get-image-channel-mean
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagecolormapcolor get-image-colormap-color
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagecolors get-image-colors
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagecolorspace get-image-colorspace
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagecompose get-image-compose
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagecompression get-image-compression
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagedelay get-image-delay
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagedepth get-image-depth
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimageextrema get-image-extrema
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagedispose get-image-dispose
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagefilename get-image-filename
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimageformat get-image-format
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagefuzz get-image-fuzz
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagegamma get-image-gamma
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagegeometry get-image-geometry
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagegravity get-image-gravity
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagegreenprimary get-image-green-primary
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimageheight get-image-height
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagehistogram get-image-histogram
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimageindex get-image-index
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimageinterlacescheme get-image-interlace-scheme
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimageiterations get-image-iterations
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagematte get-image-matte
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagemattecolor get-image-matte-color
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimageorientation get-image-orientation
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagepage get-image-page
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagepixels get-image-pixels
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimageprofile get-image-profile
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimageredprimary get-image-red-primary
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagerenderingintent get-image-rendering-intent
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimageresolution get-image-resolution
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagescene get-image-scene
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagesignature get-image-signature
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagesize get-image-size
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagetype get-image-type
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagesavedtype get-image-saved-type
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimageunits get-image-units
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagevirtualpixelmethod get-image-virtual-pixel-method
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagewhitepoint get-image-white-point
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetimagewidth get-image-width
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetnumberimages get-number-images
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetpackagename get-package-name
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetquantumdepth get-quantum-depth
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetreleasedate get-release-date
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetresourcelimit get-resource-limit
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetsamplingfactors get-sampling-factors
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetsize get-size
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickgetversion get-version
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickhaldclutimage hald-clut-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickhascolormap has-colormap
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickhasnextimage has-next-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickhaspreviousimage has-previous-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickimplodeimage implode-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickisgrayimage is-gray-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickismonochromeimage is-monochrome-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickisopaqueimage is-opaque-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickispaletteimage is-palette-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicklabelimage label-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicklevelimage level-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicklevelimagechannel level-image-channel
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickmagnifyimage magnify-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickmapimage map-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickmattefloodfillimage matte-floodfill-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickmedianfilterimage median-filter-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickminifyimage minify-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickmodulateimage modulate-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickmontageimage montage-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickmorphimages morph-images
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickmosaicimages mosaic-images
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickmotionblurimage motion-blur-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicknegateimage negate-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicknegateimagechannel negate-image-channel
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicknextimage next-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicknormalizeimage normalize-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickoilpaintimage oil-paint-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickopaqueimage opaque-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickoperatorimagechannel operator-image-channel
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickpingimage ping-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickpreviewimages preview-images
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickpreviousimage previous-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickprofileimage profile-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickquantizeimage quantize-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickquantizeimages quantize-images
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickqueryfontmetrics query-font-metrics
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickqueryfonts query-fonts
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickqueryformats query-formats
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickradialblurimage radial-blur-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickraiseimage raise-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickreadimage read-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickreadimageblob read-image-blob
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickreadimagefile read-image-file
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickreducenoiseimage reduce-noise-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickrelinquishmemory relinquish-memory
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickremoveimage remove-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickremoveimageoption remove-image-option
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickremoveimageprofile remove-image-profile
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickresetiterator reset-iterator
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickresampleimage resample-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickresizeimage resize-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickrollimage roll-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickrotateimage rotate-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksampleimage sample-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickscaleimage scale-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickseparateimagechannel separate-image-channel
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetcompressionquality set-compression-quality
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetdepth set-depth
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetfilename set-filename
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetformat set-format
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimage set-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimageattribute set-image-attribute
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagebackgroundcolor set-image-background-color
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimageblueprimary set-image-blue-primary
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagebordercolor set-image-border-color
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagecolormapcolor set-image-colormap-color
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagecolorspace set-image-colorspace
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagecompose set-image-compose
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagecompression set-image-compression
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagedelay set-image-delay
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagechanneldepth set-image-channel-depth
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagedepth set-image-depth
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagedispose set-image-dispose
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagefilename set-image-filename
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimageformat set-image-format
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagefuzz set-image-fuzz
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagegamma set-image-gamma
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagegeometry set-image-geometry
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagegravity set-image-gravity
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagegreenprimary set-image-green-primary
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimageindex set-image-index
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimageinterlacescheme set-image-interlace-scheme
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimageiterations set-image-iterations
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagematte set-image-matte
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagemattecolor set-image-matte-color
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimageoption set-image-option
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimageorientation set-image-orientation
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagepage set-image-page
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagepixels set-image-pixels
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimageprofile set-image-profile
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimageredprimary set-image-red-primary
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagerenderingintent set-image-rendering-intent
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimageresolution set-image-resolution
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagescene set-image-scene
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagetype set-image-type
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagesavedtype set-image-saved-type
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimageunits set-image-units
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagevirtualpixelmethod set-image-virtual-pixel-method
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetinterlacescheme set-interlace-scheme
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetresolution set-resolution
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetresolutionunits set-resolution-units
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetresourcelimit set-resource-limit
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetsamplingfactors set-sampling-factors
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetsize set-size
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetimagewhitepoint set-image-white-point
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksetpassphrase set-passphrase
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksharpenimage sharpen-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickshaveimage shave-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickshearimage shear-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksolarizeimage solarize-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickspreadimage spread-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicksteganoimage stegano-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickstereoimage stereo-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickstripimage strip-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickswirlimage swirl-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicktextureimage texture-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickthresholdimage threshold-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickthresholdimagechannel threshold-image-channel
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicktintimage tint-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicktransformimage transform-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicktransparentimage transparent-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magicktrimimage trim-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickunsharpmaskimage unsharp-mask-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickwaveimage wave-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickwhitethresholdimage white-threshold-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickwriteimage write-image
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickwriteimagesfile write-images-file
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickwriteimageblob write-image-blob
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickwriteimagefile write-image-file
;; http://www.graphicsmagick.org/wand/magick_wand.html#magickwriteimages write-images
;; http://www.graphicsmagick.org/wand/magick_wand.html#newmagickwand new-wand
